[package]
name = "lds_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_diamond_square = { version = "0.1", features = ["simple_view"] }
lds_simple_view = "0.1.0"